// data for the fields on the page

dataObj = {
    "wavelengthtitlefield" : "Sed nesciunt consec Sed nesciunt consec",
    "wavelengthfirstnamefield" : "Gillian Gillian Gillian Gillian Gillian Gillian Gillian Gillian Gillian",
    "wavelengthfamilynamefield": "Zia Blair",
    "wavelengthpreviousnamefield": "Kim Mcgowan",
    "Gender" : "Prefernottosay",
    "wavelengthdateofbirthfield": "1988-11-28",
    "UK Residency Status-BritishCitizen" : "BritishCitizen",
    "UK Residency Status-Refugee" : "Refugee",
    "UK Residency Status-SettledStatus" : "SettledStatus",
    "UK Residency Status-Other(pleasestate)" : "Other(pleasestate)",
    "Other(pleasestate)" : "",
    "wavelengthotherresidencystatusfield": "Soluta optio eos r",
    "wavelengthaddressfield": "Qui doloremque simil",
    "wavelengthcountyfield ": "Quo illo ad dolorem ",
    "wavelengthpostcodefield": "Irure qui est ducimu",
    "UK_Region": "Scotland",
    "wavelengthlondonboroughfield": "Commodo in possimus",
    "wavelengthphonenumberfield": "+1 (768) 957-6431",
    "wavelengthemailfield": "wykytax@mailinator.com",
    "wavelengthapplicantsigndate": "1992-06-26",
    "wavelengthhealthconsent": "on",
    "Lack_Companionship": "Someofthetime",
    "Feeling_Left_Out":"Often",
    "Feeling_isolated":"Someofthetime",
    "Feeling_Lonely": "HardlyEver",
    "General_Health": "VeryGood",
    "Current_situation_or_condition-Homeless":"on",
    "Current_situation_or_condition-Previouslyhomeless":"on",
    "Current_situation_or_condition-Alzheimers/Dementia":"on",
    "Current_situation_or_condition-Learningdisability":"on",
    "Current_situation_or_condition-Agerelatedvulnerabilites(55+)":"on",
    "Current_situation_or_condition-Addiction/substancemisuse":"on",
    "wavelengthinterviewphonefield":"+1 (546) 978-9806",
    "wavelengthinterviewemailfield ":"kokyq@mailinator.com",
    "wavelengthknowapplicantfield": "Maiores dolore labor",
    "wavelengthreferrertitlefield ": "Laudantium omnis au",
    "wavelengthreferrerfirstnamefield ":"Jerry",
    "wavelengthreferrerfamilynamefield ": "Lois Oneal",
    "wavelengthreferrerjobfield ":"Rem eligendi sed err",
    "wavelengthreferrerbodyfield ":"Eos eaque dolores iu",
    "Organisation_Type ":"Other",
    "wavelengthotherbodyfield ":"In enim quis error s",
    "wavelengthcharitynumberfield ":"Left blank",
    "wavelengthdepartmentfield ":"Recusandae Pariatur",
    "wavelengthreferreraddressfield ":"Dolor illum volupta",
    "wavelengthreferrercountyfield ":"Sunt sed cum lorem e",
    "wavelengthreferrerpostcodefield ":"Nesciunt non ipsam ",
    "Referrer_UK_Region ":"NorthernIreland",
    "wavelengthreferrerphonenumberfield ":"+1 (623) 291-5337",
    "wavelengthreferrermobilenumberfield ":"419",
    "wavelengthreferreremailfield ": "hyqofo@mailinator.com",
    "wavelengthreferrersigndate ":"1995-07-30",
    "How_did_you_hear_about_us ":"Other(pleasestate)",
    "wavelengthotherheardaboutfield ":"Voluptates omnis pra",
    "Applied_Before ":"Yes",
    "wavelengthoutcomefield ":"Qui rerum obcaecati ",
    "Accommodation ":"Hostel",
    "wavelengthhousingtypefield ":"Ipsa dolore magna a",
    "Tenant ":"Yes",
    "wavelengthorganisationnamefield ":"Logan and Terry Plc",
    "wavelengthorganisationspecialism ":"Donaldson Sutton LLC",
    "wavelengthmovingonfield ":"Rem laboriosam vero",
    "wavelengthwhyyoucannotfield ":"Optio quidem provid",
    "Is_the_applicant_disabled ":"Yes",
    "wavelengthapplicantdisabledinformationfield ":"Impedit a consequat",
    "wavelengthdeliverynamefield ":"Dolor voluptas molli",
    "wavelengthdifficultdeliveryfield ":"Est voluptas eu dol",
    "wavelengthwhyneed ":"Maiores dolore odio ",
    "Has_the_application_had_equipment_before ":"Yes",
    "wavelengthwhathappened ":"Sit ut nulla provid",
    "Kit_Wanted ":"DigitalTVwithFreeview(upto24inch)",
    "Existing_Aerial ":"Communal",
    "Existing_Services-Sky ":"Sky",
    "Existing_Services-Virgin ":"Virgin",
    "Existing_Services-Cable ":"Cable",
    "Existing_Services-Satellite ":"Satellite",
    "Existing_Services-Paidforstreaming/subscriptionservices":"Paidforstreaming/subscriptionservices",
    "Existing_Services-Internetaccess ":"Internetaccess",
    "wavelengthwhopays ":"Explicabo Est accus",
    "wavelengthaerialprovision ":"Left blank",
    "TV_Licence ":"Yes",
    "wavelengthlicenceexpirefield ":"1994-08-13",
    "wavelengthtvlicenceprovision ":"Left blank",
    "Live_Alone ":"Yes",
    "Name0":"Left blank",
    "Age0":"Left blank",
    "Relationshiptotheapplicant0":"Left blank",
    "Employmentifany0":"Left blank",
    "Benefitsreceivedandamountifany0":"Left blank",
    "Weeklycontributiontohousehold0":"Left blank",
    "Name1":"Left blank",
    "Age1":"Left blank",
    "Relationshiptotheapplicant1":"Left blank",
    "Employmentifany1":"Left blank",
    "Benefitsreceivedandamountifany1":"Left blank",
    "Weeklycontributiontohousehold1":"Left blank",
    "Name2":"Left blank",
    "Age2":"Left blank",
    "Relationshiptotheapplicant2":"Left blank",
    "Employmentifany2":"Left blank",
    "Benefitsreceivedandamountifany2":"Left blank",
    "Weeklycontributiontohousehold2":"Left blank",
    "wavelengthhowmuchcontact ":"Et molestias maiores",
    "wavelengthfamilysupport ":"Porro eveniet archi",
    "wavelengthpaidemployment ":"Amet quia sint min",
    "wavelengthpreviousemployment ":"Et quod fugiat occae",
    "Savingsinpounds0":"57",
    "CapitalHoldingsinpounds0":"42",
    "Investmentsinpounds0":"95",
    "Pensionsinpounds0":"57",
    "Creditor0":"Voluptate velit accu",
    "ReasonforNatureofdebt0":"Id quis cumque omni",
    "Amountinpounds0":"3",
    "Benefitname0":"Harriet Keller",
    "Amountpleasespecifyperweekorpermonth0":"7",
    "Reviewdate0":"20-Jun-2010",
    "Charity0":"Ut rerum sunt libero",
    "ReasonObjectiveofapplication0":"Ipsam quod odit quo ",
    "Amountrequestedgiven0":"Ipsam dicta nobis su",
    "Outcomeifknown0":"Ut aliquip qui est i",
    "Charity1":"Perspiciatis sit im",
    "ReasonObjectiveofapplication1":"Quasi sit ratione ve",
    "Amountrequestedgiven1":"Exercitation ipsum ",
    "Outcomeifknown1":"Eu vel at est tempor",
    "Charity2":"Sapiente facilis in ",
    "ReasonObjectiveofapplication2":"Harum reiciendis vol",
    "Amountrequestedgiven2":"Dolorum aliqua Et l",
    "Outcomeifknown2":"Quae fuga Officia p",
    "code ":"HjPYeyqC7v"
}

// fields which have an &nbsp; character and how many they have

nbspObj = {
    "wavelengthtitlefield": 1,
    "wavelengthfirstnamefield": 1,
    "wavelengthfamilynamefield": 1,
    "wavelengthpreviousnamefield": 1,
    "wavelengthdateofbirthfield": 1,
    "wavelengthotherresidencystatusfield": 1,
    "wavelengthaddressfield": 7,
    "wavelengthpostcodefield": 1,
    "wavelengthlondonboroughfield": 1,
    "wavelengthphonenumberfield": 1,
    "wavelengthemailfield": 1,
    "wavelengthapplicantsigndate": 1,
    "wavelengthinterviewphonefield": 1,
    "wavelengthknowapplicantfield": 31,
    "Savingsinpounds0": 1,
    "CapitalHoldingsinpounds0": 1,
    "Investmentsinpounds0": 1,
    "Pensionsinpounds0": 1
}

// fields (which are in tables) which have an &nbsp; character and how many they have

nbspSearchObj = {
    "Name" : 1,
    "Age" : 1,
    "Relationshiptotheapplicant" : 1,
    "Employmentifany" : 1,
    "Benefitsreceivedandamountifany" : 1,
    "Weeklycontributiontohousehold" : 1,
    "Creditor" : 1,
    "ReasonforNatureofdebt" : 1,
    "Amountinpounds" : 1,
    "Benefitname" : 1,
    "Amountpleasespecifyperweekorpermonth" : 1,
    "Reviewdate" : 1,
    "Charity" : 1,
    "ReasonObjectiveofapplication" : 1,
    "Amountrequestedgiven" : 1,
    "Outcomeifknown" :  1
}

// Maximum number of characters for the field

sizesObj = {
    "code": "10",
    "wavelengthtitlefield": "16",
    "wavelengthfirstnamefield": "40",
    "wavelengthfamilynamefield": "40",
    "wavelengthpreviousnamefield": "33",
    "wavelengthdateofbirthfield": "54",
    "wavelengthotherresidencystatusfield": "23",
    "wavelengthaddressfield": "137",
    "wavelengthcountyfield": "32",
    "wavelengthpostcodefield": "22",
    "wavelengthlondonboroughfield": "28",
    "wavelengthphonenumberfield": "17",
    "wavelengthemailfield": "34",
    "wavelengthapplicantsigndate": "26",
    "wavelengthinterviewphonefield": "25",
    "wavelengthinterviewemailfield": "40",
    "wavelengthknowapplicantfield": "118",
    "wavelengthreferrertitlefield": "17",
    "wavelengthreferrerfirstnamefield": "40",
    "wavelengthreferrerfamilynamefield": "63",
    "wavelengthreferrerjobfield": "63",
    "wavelengthreferrerbodyfield": "42",
    "wavelengthotherbodyfield": "27",
    "wavelengthcharitynumberfield": "17",
    "wavelengthdepartmentfield": "55",
    "wavelengthreferreraddressfield": "69",
    "wavelengthreferrercountyfield": "23",
    "wavelengthreferrerpostcodefield": "26",
    "wavelengthreferrerphonenumberfield": "51",
    "wavelengthreferrermobilenumberfield": "51",
    "wavelengthreferreremailfield": "46",
    "wavelengthreferrersigndate": "16",
    "wavelengthotherheardaboutfield": "53",
    "wavelengthoutcomefield": "89",
    "wavelengthhousingtypefield": "61",
    "wavelengthorganisationnamefield": "50",
    "wavelengthorganisationspecialism": "42",
    "wavelengthmovingonfield": "64",
    "wavelengthwhyyoucannotfield": "198",
    "Is_the_applicant_disabled": "66",
    "wavelengthapplicantdisabledinformationfield": "198",
    "wavelengthdeliverynamefield": "65",
    "wavelengthdifficultdeliveryfield": "66",
    "wavelengthwhyneed": "414",
    "wavelengthwhathappened": "111",
    "wavelengthwhopays": "31",
    "wavelengthaerialprovision": "63",
    "wavelengthlicenceexpirefield": "9",
    "wavelengthtvlicenceprovision": "65",
    "wavelengthhowmuchcontact":"552",
    "wavelengthfamilysupport":"552",
    "wavelengthpaidemployment":"67",
    "wavelengthpreviousemployment":"49",
    "Savingsinpounds0":"10",
    "CapitalHoldingsinpounds0":"10",
    "Investmentsinpounds0":"10",
    "Pensionsinpounds0":"10"
}

// Maximum number of characters for the field (when the field is a table field)

sizesSearchObj = {
    "Name":"11",
    "Age":"5",
    "Relationshiptotheapplicant":"15",
    "Employmentifany":"13",
    "Benefitsreceivedandamountifany":"11",
    "Weeklycontributiontohousehold":"12",
    "Creditor":"22",
    "ReasonforNatureofdebt":"22",
    "Amountinpounds":"14",
    "Benefitname":"22",
    "Amountpleasespecifyperweekorpermonth":"17",
    "Reviewdate":"18",
    "Charity":"12",
    "ReasonObjectiveofapplication":"23",
    "Amountrequestedgiven":"19",
    "Outcomeifknown":"15"
}